### ISSUE TITLE
key binding collision in map.lua

### ISSUE THREAD

**Issue by bryceyang** [Dualspc/nvim-config-lua#1]
<img width="914" alt="Screen Shot 2021-01-09 at 2 58 11 PM" src="https://user-images.githubusercontent.com/9302617/104085553-7746ea00-528b-11eb-84d0-9b6df0c8ed58.png">

hi, I found dup mappings in map.lua. This should be unexpected right?

**Comment by Dualspc** [comment]
Yes, thanks for the heads-up.
I remapped the "Telescope reloader" to "<leader>rl".
